<Project>
  <!-- 特定のプロジェクトだけ除外するとき -->
  <!--<ItemGroup Condition="'$(MSBuildProjectExtension)' == '.vbproj' AND '$(MSBuildProjectName)' != 'ClassLibrary3'">
    <PackageReference Include="VbNamespaceAnalyzer" Version="1.0.0" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="ProjectDir" />
  </ItemGroup>-->

  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.vbproj'">
    <PackageReference Include="VbNamespaceAnalyzer" Version="1.0.0" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="ProjectDir" />
  </ItemGroup>

  <!-- ドキュメントコメントの制約を検証するには、必ずドキュメントファイルをコンパイラで生成する必要がある -->
  <!-- これを行わないと、コードを書いているときは問題ないが、ビルドエラーが起こる -->
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vbproj'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
</Project>