<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <!--<LangVersion>latest</LangVersion>-->
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <!-- 通常の lib/ 参照としてではなく、analyzers/ 配下にのみ配置する -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoWarn>NU5128</NoWarn>

    <PackageId>VbStyleAnalyzer</PackageId>
    <Authors>Takeru Yamaguchi</Authors>
    <Description>VB.NET のコードスタイルを検証するRoslynアナライザー</Description>
    <Copyright>Copyright ©  2026 Takeru Yamaguchi</Copyright>
    <VersionPrefix>0.0.1</VersionPrefix>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <PackageProjectUrl>https://github.com/takiru/Metroit</PackageProjectUrl>
    <RepositoryUrl>https://github.com/takiru/Metroit</RepositoryUrl>
    <PackageTags>vb;style;</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>
      smaill released.
    </PackageReleaseNotes>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.14.0" />
  </ItemGroup>

  <!-- ここが重要: ビルド成果物を analyzers/dotnet/vb に配置する指定 -->
  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/vb" Visible="false" />
  </ItemGroup>
</Project>
